'use strict';
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const env=require('../config/env');
const {BCRYPT_ROUNDS,MESSAGES}=require('../config/constants');
const userModel=require('../models/userModel');
const {validateLogin,validateRegister}=require('../utils/validators');
function publicUser(user){return {id:user.id,username:user.username,email:user.email||null,role:user.role,school_id:user.school_id||null,student_id:user.student_id||null,last_login:user.last_login||null,created_at:user.created_at};}
function signToken(user){return jwt.sign({id:user.id,role:user.role,school_id:user.school_id||null},env.JWT_SECRET,{expiresIn:env.JWT_EXPIRES_IN});}
async function register(req,res){try{const {valid,errors,data}=validateRegister(req.body);if(!valid)return res.status(400).json({success:false,message:MESSAGES.VALIDATION_ERROR,errors});const {username,email,password,role}=data;if(await userModel.usernameExists(username))return res.status(409).json({success:false,message:MESSAGES.USERNAME_TAKEN});if(email&&await userModel.emailExists(email))return res.status(409).json({success:false,message:MESSAGES.EMAIL_TAKEN});const passwordHash=await bcrypt.hash(password,BCRYPT_ROUNDS);const newId=await userModel.createUser({username,email,passwordHash,role});const user=await userModel.findById(newId);const token=signToken(user);return res.status(201).json({success:true,message:'Account created successfully.',token,user:publicUser(user)});}catch(err){console.error('[authController.register]',err.message);return res.status(500).json({success:false,message:MESSAGES.SERVER_ERROR});}}
async function login(req,res){try{const {valid,errors,data}=validateLogin(req.body);if(!valid)return res.status(400).json({success:false,message:MESSAGES.VALIDATION_ERROR,errors});const user=data.login.includes('@')?await userModel.findByEmail(data.login):await userModel.findByUsername(data.login);const hashToCheck=user?user.password_hash:'$2b$12$invalidhashpadding000000000000000000000000000000000000';const passwordMatch=await bcrypt.compare(data.password,hashToCheck);if(!user||!passwordMatch)return res.status(401).json({success:false,message:MESSAGES.INVALID_CREDENTIALS});if(!user.is_active)return res.status(403).json({success:false,message:MESSAGES.ACCOUNT_INACTIVE});await userModel.touchLastLogin(user.id);const token=signToken(user);return res.status(200).json({success:true,message:'Login successful.',token,user:publicUser(user)});}catch(err){console.error('[authController.login]',err.message);return res.status(500).json({success:false,message:MESSAGES.SERVER_ERROR});}}
async function me(req,res){try{const user=await userModel.findById(req.user.id);if(!user)return res.status(404).json({success:false,message:MESSAGES.USER_NOT_FOUND});return res.status(200).json({success:true,user:publicUser(user)});}catch(err){console.error('[authController.me]',err.message);return res.status(500).json({success:false,message:MESSAGES.SERVER_ERROR});}}
function logout(_req,res){return res.status(200).json({success:true,message:'Logged out successfully. Please discard your token.'});}
module.exports={register,login,me,logout};
