'use strict';
const {db}=require('../config/db');
const scholarshipModel=require('../models/scholarshipModel');
const engine=require('../services/scholarshipEngine');
const {MESSAGES,ROLES}=require('../config/constants');
function schoolScope(req){return Number(req.user.school_id)||0;}
async function listRules(req,res){try{const schoolId=schoolScope(req);if(!schoolId)return res.status(403).json({success:false,message:MESSAGES.FORBIDDEN});const rules=await scholarshipModel.findRulesBySchool(schoolId,false);return res.json({success:true,rules});}catch(err){return res.status(500).json({success:false,message:MESSAGES.SERVER_ERROR});}}
async function createRule(req,res){try{const schoolId=schoolScope(req);if(!schoolId)return res.status(403).json({success:false,message:MESSAGES.FORBIDDEN});const b=req.body||{};if(!b.rule_name||b.rule_type!=='attendance_threshold'||!Number.isFinite(Number(b.threshold_value))||!Number.isInteger(Number(b.window_days))||Number(b.window_days)<1||!['fee_discount_percent','fee_discount_fixed'].includes(b.award_type)||!Number.isFinite(Number(b.award_value)))return res.status(400).json({success:false,message:'Invalid scholarship rule.'});const id=await scholarshipModel.createRule({school_id:schoolId,rule_name:String(b.rule_name).trim(),rule_type:b.rule_type,threshold_value:Number(b.threshold_value),window_days:Number(b.window_days),award_type:b.award_type,award_value:Number(b.award_value)});return res.status(201).json({success:true,rule:await scholarshipModel.findRuleById(id)});}catch(err){return res.status(500).json({success:false,message:MESSAGES.SERVER_ERROR});}}
async function updateRule(req,res){try{const schoolId=schoolScope(req);const id=Number(req.params.id);const rule=await scholarshipModel.findRuleById(id);if(!rule||rule.school_id!==schoolId)return res.status(404).json({success:false,message:'Scholarship rule not found.'});const b=req.body||{};const fields=[];const args=[];for(const [k,v] of [['rule_name',b.rule_name],['threshold_value',b.threshold_value],['window_days',b.window_days],['award_type',b.award_type],['award_value',b.award_value],['is_active',b.is_active]]){if(v!==undefined){if(k==='award_type'&&!['fee_discount_percent','fee_discount_fixed'].includes(v))return res.status(400).json({success:false,message:'Invalid award_type.'});fields.push(`${k}=?`);args.push(k==='rule_name'?String(v).trim():Number(v));}}if(!fields.length)return res.status(400).json({success:false,message:'No supported fields supplied.'});args.push(id);await db.execute({sql:`UPDATE scholarship_rules SET ${fields.join(', ')},updated_at=datetime('now') WHERE id=?`,args});return res.json({success:true,rule:await scholarshipModel.findRuleById(id)});}catch(err){return res.status(500).json({success:false,message:MESSAGES.SERVER_ERROR});}}
async function deactivateRule(req,res){try{const rule=await scholarshipModel.findRuleById(Number(req.params.id));if(!rule||rule.school_id!==schoolScope(req))return res.status(404).json({success:false,message:'Scholarship rule not found.'});await scholarshipModel.deactivateRule(rule.id);return res.json({success:true,message:'Scholarship rule deactivated.'});}catch(err){return res.status(500).json({success:false,message:MESSAGES.SERVER_ERROR});}}
async function evaluateStudent(req,res){try{const studentId=Number(req.params.studentId),feeId=Number(req.params.feeId);if(!studentId||!feeId)return res.status(400).json({success:false,message:'Invalid student or fee ID.'});const result=await engine.evaluateStudentScholarships(studentId,feeId);return res.json({success:true,result});}catch(err){return res.status(err.statusCode||500).json({success:false,message:err.statusCode?err.message:MESSAGES.SERVER_ERROR});}}
async function runBatch(req,res){try{const result=await engine.runScholarshipBatch(schoolScope(req));return res.json({success:true,result});}catch(err){return res.status(err.statusCode||500).json({success:false,message:err.statusCode?err.message:MESSAGES.SERVER_ERROR});}}
async function studentSummary(req,res){try{const result=await engine.getStudentScholarshipSummary(Number(req.params.studentId));return res.json({success:true,...result});}catch(err){return res.status(500).json({success:false,message:MESSAGES.SERVER_ERROR});}}
module.exports={listRules,createRule,updateRule,deactivateRule,evaluateStudent,runBatch,studentSummary};
