'use strict';
const { Router } = require('express');
const rateLimit = require('express-rate-limit');
const authController = require('../../../controllers/authController');
const { authenticate } = require('../../../middleware/auth');
const router = Router();
const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 10, standardHeaders: true, legacyHeaders: false, message: { success: false, message: 'Too many requests from this IP. Please try again in 15 minutes.' } });
router.post('/register', authLimiter, authController.register);
router.post('/login', authLimiter, authController.login);
router.get('/me', authenticate, authController.me);
router.post('/logout', authenticate, authController.logout);
module.exports = router;
