'use strict';
const { db } = require('../config/db');

function normalizeRule(row) {
  if (!row) return null;
  return { ...row, name: row.rule_name, discount_type: row.award_type === 'fee_discount_percent' ? 'percent' : 'fixed_usdc', discount_value: row.award_value };
}
async function findRuleById(id) { const r=await db.execute({sql:'SELECT * FROM scholarship_rules WHERE id = ? LIMIT 1',args:[id]}); return normalizeRule(r.rows[0]); }
async function findActiveRulesBySchool(schoolId) { const r=await db.execute({sql:'SELECT * FROM scholarship_rules WHERE school_id = ? AND is_active = 1 ORDER BY created_at ASC, id ASC',args:[schoolId]}); return r.rows.map(normalizeRule); }
async function findAllRulesBySchool(schoolId) { const r=await db.execute({sql:'SELECT * FROM scholarship_rules WHERE school_id = ? ORDER BY created_at ASC, id ASC',args:[schoolId]}); return r.rows.map(normalizeRule); }
async function findRulesBySchool(schoolId, activeOnly=true) { return activeOnly ? findActiveRulesBySchool(schoolId) : findAllRulesBySchool(schoolId); }
async function createRule({school_id,name,rule_type,threshold_value,discount_type,discount_value}) { const award_type=discount_type==='percent'?'fee_discount_percent':'fee_discount_fixed'; const r=await db.execute({sql:`INSERT INTO scholarship_rules (school_id, rule_name, rule_type, threshold_value, window_days, award_type, award_value) VALUES (?, ?, ?, ?, ?, ?, ?)`,args:[school_id,name,rule_type,threshold_value,30,award_type,discount_value]}); return r.lastInsertRowid; }
async function updateRule(id,fields) { const map={name:'rule_name',threshold_value:'threshold_value',discount_type:'award_type',discount_value:'award_value',is_active:'is_active'}; const entries=Object.entries(fields||{}).filter(([k,v])=>Object.prototype.hasOwnProperty.call(map,k)&&v!==undefined); if(!entries.length)return findRuleById(id); const set=[];const args=[]; for(const [key,value] of entries){set.push(`${map[key]} = ?`);args.push(key==='discount_type'?(value==='percent'?'fee_discount_percent':'fee_discount_fixed'):value);} args.push(id); await db.execute({sql:`UPDATE scholarship_rules SET ${set.join(', ')}, updated_at = datetime('now') WHERE id = ?`,args}); return findRuleById(id); }
async function deactivateRule(id){return updateRule(id,{is_active:0});}
async function findApplicationByStudentAndRule(studentId,ruleId,feeId){const r=await db.execute({sql:`SELECT * FROM scholarship_awards WHERE student_id = ? AND rule_id = ? AND fee_id = ? AND status = 'applied' LIMIT 1`,args:[studentId,ruleId,feeId]});return r.rows[0]||null;}
async function createApplication({student_id,rule_id,fee_id,discount_amount,rule_snapshot}){const snap=rule_snapshot||{};const awardType=snap.discount_type==='percent'?'fee_discount_percent':'fee_discount_fixed';const attendance=Number(snap.eval_stats?.percentage||0);const window=snap.window||{};const r=await db.execute({sql:`INSERT INTO scholarship_awards (rule_id, student_id, fee_id, award_type, award_value, discount_applied, attendance_pct, evaluated_from, evaluated_to, status, skip_reason) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'applied', NULL)`,args:[rule_id,student_id,fee_id||null,awardType,Number(snap.discount_value||discount_amount),discount_amount,attendance,window.fromDate||new Date().toISOString().slice(0,10),window.toDate||new Date().toISOString().slice(0,10)]});return r.lastInsertRowid;}
async function findApplicationsByStudent(studentId){const r=await db.execute({sql:`SELECT sa.*, sr.rule_name, sr.rule_type FROM scholarship_awards sa JOIN scholarship_rules sr ON sr.id = sa.rule_id WHERE sa.student_id = ? ORDER BY sa.created_at DESC, sa.id DESC`,args:[studentId]});return r.rows;}
async function findAwardsByStudent(studentId){return findApplicationsByStudent(studentId);}
async function findAwardsBySchool(schoolId){const r=await db.execute({sql:`SELECT sa.*, sr.rule_name, sr.rule_type, s.name AS student_name, s.roll_no FROM scholarship_awards sa JOIN scholarship_rules sr ON sr.id = sa.rule_id JOIN students s ON s.id = sa.student_id WHERE sr.school_id = ? ORDER BY sa.created_at DESC`,args:[schoolId]});return r.rows;}
async function awardAlreadyExists(ruleId,studentId,evaluatedFrom,evaluatedTo){const r=await db.execute({sql:`SELECT 1 FROM scholarship_awards WHERE rule_id = ? AND student_id = ? AND evaluated_from = ? AND evaluated_to = ? AND status = 'applied' LIMIT 1`,args:[ruleId,studentId,evaluatedFrom,evaluatedTo]});return r.rows.length>0;}
async function createAward(args){return createApplication({student_id:args.student_id,rule_id:args.rule_id,fee_id:args.fee_id,discount_amount:args.discount_applied,rule_snapshot:{discount_type:args.award_type==='fee_discount_percent'?'percent':'fixed_usdc',discount_value:args.award_value,eval_stats:{percentage:args.attendance_pct},window:{fromDate:args.evaluated_from,toDate:args.evaluated_to}}});}
async function updateApplicationStatus(id,patch){if(!patch?.status||!['applied','skipped','failed'].includes(patch.status))return findApplicationById(id);await db.execute({sql:'UPDATE scholarship_awards SET status = ?, skip_reason = ? WHERE id = ?',args:[patch.status,patch.status==='skipped'?(patch.skip_reason||null):null,id]});return findApplicationById(id);}
async function findApplicationById(id){const r=await db.execute({sql:'SELECT * FROM scholarship_awards WHERE id = ? LIMIT 1',args:[id]});return r.rows[0]||null;}
module.exports={findRuleById,findActiveRulesBySchool,findAllRulesBySchool,findRulesBySchool,createRule,updateRule,deactivateRule,findApplicationByStudentAndRule,createApplication,findApplicationsByStudent,findAwardsByStudent,findAwardsBySchool,awardAlreadyExists,createAward,updateApplicationStatus,findApplicationById};
